Lesson2 calculator layout
joltyi/Android1 pull request #2
Opened 2021-06-06 02:24 UTC by joltyi

2021-06-06 02:41 UTC, joltyi commented
Из текущих проблем:  android:background не применяется на кнопках. Не понимаю почему.

2021-06-06 14:19 UTC, DwarfPorter commented
![image](https://user-images.githubusercontent.com/31162829/120927925-47412d00-c6eb-11eb-9a49-e639b42a42b4.png)

2021-06-06 14:19 UTC, DwarfPorter commented
Не хватает файлов для запуска. Нет градл основного файла.

2021-06-06 14:20 UTC, DwarfPorter requested changes
Пожалуйста, добавьте все необходимые файлы

2021-06-06 14:59 UTC, joltyi commented
@DwarfPorter Приношу свои извинения. Добавил файлы.

2021-06-08 15:11 UTC, DwarfPorter approved these changes

2021-06-08 15:13 UTC, merged